-- AlterTable
ALTER TABLE "Server" ALTER COLUMN "statusFrontEnd" SET DEFAULT 'UNINITIALIZED',
ALTER COLUMN "statusBackEnd" SET DEFAULT 'UNINITIALIZED',
ALTER COLUMN "statusDatabase" SET DEFAULT 'UNINITIALIZED';
